CREATE TABLE GAME_STORE.STATES_TYPES(
    ST_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL TIPO DE ESTADO',
    ST_TYPE_DESCRIPTION VARCHAR(100) NOT NULL COMMENT 'DESCRIPCION DEL TIPO DE ESTADO',
    ST_TYPE_ALIAS VARCHAR(5) NOT NULL COMMENT 'ALIAS IDENTIFICADOR DEL TIPO DE ESTADO'
) COMMENT 'TABLA PARA LOS TIPOS DE ESTADOS';
CREATE UNIQUE INDEX UQ_ST_TYPE_ALIAS ON GAME_STORE.STATES_TYPES(ST_TYPE_ALIAS);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.STATES_TYPES TO GAME_STORE;

CREATE TABLE GAME_STORE.STATES(
    STATE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL ESTADO',
    STATE_DESC VARCHAR(100) NOT NULL COMMENT 'DESCRIPCION DEL ESTADO',
    STATE_ALIAS VARCHAR(10) NOT NULL COMMENT 'ALIAS IDENTIFICADOR DEL ESTADO',
    STATE_TYPE INT NOT NULL COMMENT 'TIPO DE ESTADO'
) COMMENT 'TABLA PARA LOS ESTADOS';
ALTER TABLE GAME_STORE.STATES ADD CONSTRAINT FK_STATE_TYPE FOREIGN KEY (STATE_TYPE) REFERENCES GAME_STORE.STATES_TYPES(ST_TYPE_ID);
CREATE UNIQUE INDEX UQ_STATE_ALIAS ON GAME_STORE.STATES(STATE_ALIAS);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.STATES TO GAME_STORE;

CREATE TABLE GAME_STORE.DOC_TYPES(
    DOC_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL TIPO DE DOCUMENTO',
    DOC_DESCRIPTION VARCHAR(100) NOT NULL COMMENT 'DESCRIPCION DEL TIPO DE DOCUMENTO',
    DOC_INITIALS VARCHAR(5) COMMENT  'ABREVIACION DEL TIPO DE DOCUMENTO'
) COMMENT 'TABLA PARA LOS TIPOS DE DOCUMENTOS EXISTENTES';
CREATE UNIQUE INDEX UQ_DOC_TYPE ON GAME_STORE.DOC_TYPES(DOC_INITIALS);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.DOC_TYPES TO GAME_STORE;

CREATE TABLE GAME_STORE.USERS(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR UNICO DE CADA USUARIO',
    USER_NAMES VARCHAR(150) NOT NULL COMMENT 'NOMBRE(S) DEL USUARIO',    
    LAST_NAME1 VARCHAR(100) NOT NULL COMMENT 'PRIMER APELLIDO DEL USUARIO',
    LAST_NAME2 VARCHAR(100) COMMENT 'SEGUNDO APELLIDO DEL USUARIO',
    DOC_TYPE_ID INT NOT NULL COMMENT 'TIPO DE DOCUMENTO DEL USUARIO',
    DOC_NUMBER VARCHAR(50) NOT NULL COMMENT 'NUMERO DE DOCUMENTO DEL USUARIO'
) COMMENT 'TABLA PARA LOS USUARIOS (VENDEDORES)';
ALTER TABLE GAME_STORE.USERS ADD CONSTRAINT FK_USER_DOC_TYPE FOREIGN KEY (DOC_TYPE_ID) REFERENCES GAME_STORE.DOC_TYPES(DOC_TYPE_ID);
CREATE UNIQUE INDEX UQ_USER_DOCUMENT ON GAME_STORE.USERS(DOC_TYPE_ID,DOC_NUMBER);
GRANT SELECT,INSERT,UPDATE,DELETE, REFERENCES ON GAME_STORE.USERS TO GAME_STORE;

CREATE TABLE GAME_STORE.HIST_USER_STATES(
	USER_STATE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR HISTORIAL DE ESTADOS DE USUARIOS',
    USER_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL USUARIO',
    STATE_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL ESTADO',
    MODIFICATION_DATE DATE NOT NULL COMMENT 'FECHA EN QUE EL USUARIO CAMBIA DE ESTADO'
    );
ALTER TABLE GAME_STORE.HIST_USER_STATES ADD CONSTRAINT FK_HIST_ID_USER FOREIGN KEY (USER_ID) REFERENCES GAME_STORE.USERS(USER_ID);
ALTER TABLE GAME_STORE.HIST_USER_STATES ADD CONSTRAINT FK_HIST_USER_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES GAME_STORE.STATES(STATE_ID);
GRANT SELECT,INSERT,UPDATE,DELETE, REFERENCES ON GAME_STORE.HIST_USER_STATES TO GAME_STORE;

CREATE TABLE GAME_STORE.USERS_SECURITY(
	ID_USER_SECURITY INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DE SEGURIDAD DE USUARIOS',
    USER_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL USUARIO',
    USER_PASSWORD varchar(100) NOT NULL COMMENT 'CONTRASEÑA PARA INICIAR SESION'
    );
ALTER TABLE GAME_STORE.USERS_SECURITY ADD CONSTRAINT FK_SEC_ID_USER FOREIGN KEY (USER_ID) REFERENCES GAME_STORE.USERS(USER_ID);
GRANT SELECT,INSERT,UPDATE,DELETE, REFERENCES ON GAME_STORE.USERS_SECURITY TO GAME_STORE;

CREATE TABLE GAME_STORE.CUSTOMERS(
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR UNICO DE LOS CLIENTES',
    CUSTOMER_NAMES VARCHAR(150) NOT NULL COMMENT 'NOMBRE(S) DEL CLIENTE',    
    CUSTOMER_LAST_NAME1 VARCHAR(100) NOT NULL COMMENT 'PRIMER APELLIDO DEL CLIENTE',
    CUSTOMER_LAST_NAME2 VARCHAR(100) COMMENT 'SEGUNDO APELLIDO DEL CLIENTE',
    DOC_TYPE_ID INT NOT NULL COMMENT 'TIPO DE DOCUMENTO DEL CLIENTE',
    DOC_NUMBER VARCHAR(50) NOT NULL COMMENT 'NUMERO DE DOCUMENTO DEL CLIENTE',
    ADDRESS VARCHAR(100) NOT NULL COMMENT 'DIRECCION DE RESIDENCIA DEL CLIENTE',
    AGE INT NOT NULL COMMENT 'EDAD DEL CLIENTE',
    PHONE INT UNSIGNED NOT NULL COMMENT 'TELÉFONO DE CONTACTO DEL CLIENTE',
    CELLPHONE INT UNSIGNED NOT NULL COMMENT 'CELULAR DE CONTACTO A DEL CLIENTE'
) COMMENT 'TABLA PARA LOS CLIENTES';
ALTER TABLE GAME_STORE.CUSTOMERS ADD CONSTRAINT FK_CUSTOMER_DOC_TYPE FOREIGN KEY (DOC_TYPE_ID) REFERENCES GAME_STORE.DOC_TYPES(DOC_TYPE_ID);
CREATE UNIQUE INDEX UQ_CUSTOMER_DOCUMENT ON GAME_STORE.CUSTOMERS(DOC_TYPE_ID,DOC_NUMBER);
GRANT SELECT,INSERT,UPDATE,DELETE, REFERENCES ON GAME_STORE.CUSTOMERS TO GAME_STORE;

CREATE TABLE GAME_STORE.CHARACTER_ROLS(
    CHARACTER_ROL_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL ROL DE LOS PARTICIPANTES',
    CHARACTER_ROL_DESC VARCHAR(100) NOT NULL COMMENT 'DESCRIPCION DEL ROL'
) COMMENT 'TABLA PARA LOS ROLES DE LOS PARTICIPANTES DE LAS PELICULAS';
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.CHARACTER_ROLS TO GAME_STORE;

CREATE TABLE GAME_STORE.CHARACTERS(
    CHARACTER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL PARTICIPANTE ',
    CHARACTER_NAME VARCHAR(200) NOT NULL COMMENT 'NOMBRE DEL PARTICIPE EN LAS PELICULAS'
) COMMENT 'TABLA PARA LOS PARTICIPANTES DE LAS PELICULAS';
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.CHARACTERS TO GAME_STORE;

CREATE TABLE GAME_STORE.BRANDS(
    BRAND_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DE LA MARCA ',
    BRAND_NAME VARCHAR(200) NOT NULL COMMENT 'NOMBRE DE LA MARCA'
) COMMENT 'TABLA PARA LAS MARCAS DE LAS PELICULAS';
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.BRANDS TO GAME_STORE;

CREATE TABLE GAME_STORE.TECHNOLOGIES(
    TECH_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DE TECNOLOGIA',
    TECH_NAME VARCHAR(200) NOT NULL COMMENT 'NOMBRE DE LA TECNOLOGIA'
) COMMENT 'TABLA PARA LAS TECNOLOGIAS DE LAS PELICULAS';
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.TECHNOLOGIES TO GAME_STORE;

CREATE TABLE GAME_STORE.PRODUCTS(
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL PRODUCTO',
    PRODUCT_NAME VARCHAR(200) NOT NULL COMMENT 'NOMBRE DE LA PELICULA',
    PRODUCT_DESCRIPTION VARCHAR(200) NOT NULL COMMENT 'DESCRIPCION BREVE DE LA PELICULA',
    ANIO DATE NOT NULL COMMENT 'AÑO DE LANZAMIENTO DE LA PELICULA',
    BRAND_ID INT NOT NULL COMMENT 'IDENTIFICADO DE LA MARCA DE LA PELICULA',
    PRODUCT_VALUE INT NOT NULL COMMENT 'COSTO DE ALQUILER DEL PRODUCTO'
) COMMENT 'TABLA PARA LAS PELICULAS';
ALTER TABLE GAME_STORE.PRODUCTS ADD CONSTRAINT FK_PRODUCT_BRAND FOREIGN KEY (BRAND_ID) REFERENCES GAME_STORE.BRANDS(BRAND_ID);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.PRODUCTS TO GAME_STORE;

CREATE TABLE GAME_STORE.PRODUCTS_TECHNOLOGIES(
    PRODUCT_TECH_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DE TECNOLOGIA-PRODUCTO',
    PRODUCT_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL PRODUCTO',
    TECH_ID INT NOT NULL COMMENT 'IDENTIFICADOR DE TECNOLOGIA',
    QUANTITY INT NOT NULL COMMENT 'CANTIDAD DISPONIBLE PARA ALQUILER'
) COMMENT 'TABLA PARA REGISTRAR LOS PRODUCTOS POR TECNOLOGIAS';
ALTER TABLE GAME_STORE.PRODUCTS_TECHNOLOGIES ADD CONSTRAINT FK_PRODUCT_TECH_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES GAME_STORE.PRODUCTS(PRODUCT_ID);
ALTER TABLE GAME_STORE.PRODUCTS_TECHNOLOGIES ADD CONSTRAINT FK_PRODUCT_TECH_TECH FOREIGN KEY (TECH_ID) REFERENCES GAME_STORE.TECHNOLOGIES(TECH_ID);
CREATE UNIQUE INDEX UQ_PROD_TECH ON GAME_STORE.PRODUCTS_TECHNOLOGIES(PRODUCT_ID,TECH_ID);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.PRODUCTS_TECHNOLOGIES TO GAME_STORE;

CREATE TABLE GAME_STORE.PRODUCTS_CHARACTERS(
    PROD_CHARACTER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DE PARTICIPE EN LA PELICULA',
    PRODUCT_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL PRODUCTO',
    CHARACTER_ID INT NOT NULL COMMENT 'IDENTIFICADOR DE PARTICIPE',
    CHARACTER_ROL_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL ROL DEL PARTICIPE EN EL PRODUCTO (PELICULA)'
) COMMENT 'TABLA PARA REGISTRAR LOS PRODUCTOS POR TECNOLOGIAS';
ALTER TABLE GAME_STORE.PRODUCTS_CHARACTERS ADD CONSTRAINT FK_PPROD_CHARACTER_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES GAME_STORE.PRODUCTS(PRODUCT_ID);
ALTER TABLE GAME_STORE.PRODUCTS_CHARACTERS ADD CONSTRAINT FK_PROD_CHARACTER_CHAR FOREIGN KEY (CHARACTER_ID) REFERENCES GAME_STORE.CHARACTERS(CHARACTER_ID);
ALTER TABLE GAME_STORE.PRODUCTS_CHARACTERS ADD CONSTRAINT FK_PROD_CHARACTER_ROL FOREIGN KEY (CHARACTER_ROL_ID) REFERENCES GAME_STORE.CHARACTER_ROLS(CHARACTER_ROL_ID);
CREATE UNIQUE INDEX UQ_PROD_CHAR_ROL ON GAME_STORE.PRODUCTS_CHARACTERS(PRODUCT_ID,CHARACTER_ID,CHARACTER_ROL_ID);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.PRODUCTS_CHARACTERS TO GAME_STORE;

CREATE TABLE GAME_STORE.RENTAL_HEADERS(
    ID_RENTAL INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DE LA RENTA',
    USER_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL USUARIO',
    CUSTOMER_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL CLIENTE',
    TOTAL_VALUE INT NOT NULL COMMENT 'VALOR DE ALQUILER TOTAL',
    RENTAL_DATE DATE NOT NULL COMMENT 'FECHA EN QUE SE REALIZA EL ALQUILER',
    RENTAL_FINISH DATE NOT NULL COMMENT 'FECHA EN QUE SE VENCE EL ALQUILER, ACÁ SE DEBE DEVOLVER LOS PRODUCTOS ALQUILADOS'
) COMMENT 'TABLA PARA REGISTRAR EL ALQUILER DE PELICULAS';
ALTER TABLE GAME_STORE.RENTAL_HEADERS ADD CONSTRAINT FK_RENTAL_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES GAME_STORE.CUSTOMERS(CUSTOMER_ID);
ALTER TABLE GAME_STORE.RENTAL_HEADERS ADD CONSTRAINT FK_RENTAL_USER FOREIGN KEY (USER_ID) REFERENCES GAME_STORE.USERS(USER_ID);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.RENTAL_HEADERS TO GAME_STORE;

CREATE TABLE GAME_STORE.RENTAL_DETAIL(
    ID_RENTAL_DETAIL INT AUTO_INCREMENT PRIMARY KEY COMMENT 'IDENTIFICADOR DEL DETALLE LA RENTA',
    ID_RENTAL INT NOT NULL COMMENT 'IDENTIFICADOR DE LA RENTA',
    PRODUCT_ID INT NOT NULL COMMENT 'IDENTIFICADOR DEL PRODUCTO',
    PRODUCT_VALUE INT NOT NULL COMMENT 'VALOR DE ALQUILER DEL PRODUCTO',
    RETURNED BOOLEAN NOT NULL COMMENT 'INDICADOR DE DEVOLUCION DEL PRODUCTO'
) COMMENT 'TABLA PARA REGISTRAR EL DETALLE DEL ALQUILER DE PELICULAS';
ALTER TABLE GAME_STORE.RENTAL_DETAIL ADD CONSTRAINT FK_RENTAL_DET_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES GAME_STORE.PRODUCTS(PRODUCT_ID);
ALTER TABLE GAME_STORE.RENTAL_DETAIL ADD CONSTRAINT FK_RENTAL_HEADER FOREIGN KEY (ID_RENTAL) REFERENCES GAME_STORE.RENTAL_HEADERS(ID_RENTAL);
GRANT SELECT,INSERT,UPDATE,DELETE ON GAME_STORE.RENTAL_DETAIL TO GAME_STORE;

COMMIT;